# Single-cell wrangling cookbook

## Contents

- [Load an annotated object](#load-an-annotated-object)
- [Attach donor metadata](#attach-donor-metadata)
- [Filter a cohort](#filter-a-cohort)
- [Select an analysis schema](#select-an-analysis-schema)
- [Order, derive, and summarize](#order-derive-and-summarize)
- [Reuse groups](#reuse-groups)
- [Build tidy tables](#build-tidy-tables)
- [Compose with project code](#compose-with-project-code)

A broad tour of the verb surface, run against Scanpy's PBMC3K: 2,638 cells,
1,838 highly variable genes in `X`, Louvain cell-type labels, QC metrics,
PCA/UMAP/t-SNE embeddings, PCA loadings in `varm`, and log-normalised counts
for 13,714 genes in `.raw`.

AnnData-returning verbs preserve axis alignment and continue through `.ap`.
Grouped verbs keep their grouping until `ungroup()`. Summaries and extraction
make an explicit transition to pandas.

```{note}
`X` holds **scaled** values in this dataset, so expression examples read `raw=`.
Only the `donor_id` column is synthetic; it is created where it first appears.
```

In [1]:
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "anndata",
#     "annplyr",
#     "numpy",
#     "pandas",
#     "scanpy",
# ]
# ///

## Load an annotated object

In [2]:
import numpy as np
import pandas as pd
import scanpy as sc

import annplyr as ap

adata = sc.datasets.pbmc3k_processed()
adata

AnnData object with n_obs × n_vars = 2638 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Importing annplyr registers the accessor without changing the object.

In [3]:
hasattr(adata, "ap")

True

## Attach donor metadata

In [4]:
adata.obs["donor_id"] = [f"donor_{i % 3 + 1}" for i in range(adata.n_obs)]

donor_table = pd.DataFrame(
    {
        "donor_id": ["donor_1", "donor_2", "donor_3"],
        "condition": ["control", "stimulated", "stimulated"],
    }
)

joined = adata.ap.left_join(donor_table, by="donor_id", relationship="many-to-one")
joined.obs[["louvain", "donor_id", "condition"]].head()

                          louvain donor_id   condition
index
AAACATACAACCAC-1      CD4 T cells  donor_1     control
AAACATTGAGCTAC-1          B cells  donor_2  stimulated
AAACATTGATCAGC-1      CD4 T cells  donor_3  stimulated
AAACCGTGCTTCCG-1  CD14+ Monocytes  donor_1     control
AAACCGTGTATGCG-1         NK cells  donor_2  stimulated

## Filter a cohort

In [5]:
adata.ap.filter(obs=ap.col("louvain") == "B cells")

AnnData object with n_obs × n_vars = 342 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

This is equivalent to standard AnnData indexing:

In [6]:
adata[adata.obs["louvain"] == "B cells", :]

View of AnnData object with n_obs × n_vars = 342 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Expressions combine with `&` and `|`; a tuple of predicates applies as an implicit `AND`.

In [7]:
adata.ap.filter(
    obs=(
        ap.col("louvain") == "B cells",
        ap.col("n_genes") >= 800,
    )
)

AnnData object with n_obs × n_vars = 85 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [8]:
adata.ap.filter(
    obs=(ap.col("louvain").is_in(["NK cells", "CD8 T cells"])) | (ap.col("n_counts") > 6000)
)

AnnData object with n_obs × n_vars = 491 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Filtering on `var` subsets features.

In [9]:
adata.ap.filter(var=ap.col("n_cells") >= 1500)

AnnData object with n_obs × n_vars = 2638 × 21
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Filtering on `raw` reads expression by gene name. Use `x=` for `X`, or pass `layer=` to redirect to a named layer.

In [10]:
adata.ap.filter(raw=ap.col("MS4A1") > 2)

AnnData object with n_obs × n_vars = 9 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Sources can be combined in one call.

In [11]:
adata.ap.filter(
    obs=ap.col("percent_mito") < 0.03,
    var=ap.col("n_cells") >= 500,
    raw=ap.col("CD79A") > 0,
)

AnnData object with n_obs × n_vars = 359 × 208
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

`obs_names` and `var_names` match against axis labels themselves.

In [12]:
adata.ap.filter(obs_names=ap.obs_names.str.starts_with("AAAC"))

AnnData object with n_obs × n_vars = 12 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

The tidyselect-aware `if_any` and `if_all` helpers reduce a predicate across selected columns.

In [13]:
adata.ap.filter(obs=ap.if_any(ap.starts_with("n_"), lambda column: ap.col(column) > 5000))

AnnData object with n_obs × n_vars = 64 × 1838
    obs: 'n_genes', 'percent_mito', 'n_counts', 'louvain', 'donor_id'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

## Select an analysis schema

In [14]:
adata.ap.select(
    obs=["louvain", "n_genes"],
    var=["n_cells"],
    x=["MS4A1", "CD79A", "NKG7"],
)

AnnData object with n_obs × n_vars = 2638 × 3
    obs: 'louvain', 'n_genes'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

Tidyselect-style helpers make common selections compact.

In [15]:
adata.ap.select(obs=ap.starts_with("n_"))

AnnData object with n_obs × n_vars = 2638 × 1838
    obs: 'n_genes', 'n_counts'
    var: 'n_cells'
    uns: 'draw_graph', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_tsne', 'X_umap', 'X_draw_graph_fr'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

`pick` returns a selector object for extraction contexts.

In [16]:
adata.ap.to_df(obs=ap.pick(ap.starts_with("n_"))).head()

                  n_genes  n_counts
index
AAACATACAACCAC-1      781    2419.0
AAACATTGAGCTAC-1     1352    4903.0
AAACATTGATCAGC-1     1131    3147.0
AAACCGTGCTTCCG-1      960    2639.0
AAACCGTGTATGCG-1      522     980.0

## Order, derive, and summarize

In [17]:
adata.ap.arrange(obs=ap.desc("n_counts")).obs[["louvain", "n_counts"]].head()

                          louvain  n_counts
index
ACGAACTGGCTATG-1   Megakaryocytes    8875.0
GGGCCAACCTTGGA-1  Dendritic cells    8415.0
CAGGTTGAGGATCT-1          B cells    8011.0
ACGAGGGACAGGAG-1  Dendritic cells    7928.0
CATACTTGGGTTAC-1      CD4 T cells    7167.0

In [18]:
adata.ap.slice_head(n=3).obs[["louvain", "n_counts"]]

                      louvain  n_counts
index
AAACATACAACCAC-1  CD4 T cells    2419.0
AAACATTGAGCTAC-1      B cells    4903.0
AAACATTGATCAGC-1  CD4 T cells    3147.0

In [19]:
adata.ap.slice_max(ap.col("n_cells"), n=5, axis="var").var

        n_cells
index
CYBA       2277
S100A6     2109
UBB        2094
CD37       2063
ARPC1B     2004

`mutate` writes new `obs` or `var` metadata. Matrix, layer, `raw`, `obsm`, and `varm` sources are read-only.

In [20]:
adata.ap.mutate(
    obs={"deep": ap.col("n_counts") >= 2000},
    raw={"b_markers": (ap.col("MS4A1") > 0) & (ap.col("CD79A") > 0)},
    obsm={"X_umap": {"umap1": ap.col("0")}},
).obs.head()

,n_genes,percent_mito,n_counts,louvain,donor_id,deep,b_markers,umap1
index,,,,,,,,
AAACATACAACCAC-1,781,0.030178,2419.0,CD4 T cells,donor_1,True,False,1.352856
AAACATTGAGCTAC-1,1352,0.037936,4903.0,B cells,donor_2,True,True,-0.478024
AAACATTGATCAGC-1,1131,0.008897,3147.0,CD4 T cells,donor_3,True,False,2.165889
AAACCGTGCTTCCG-1,960,0.017431,2639.0,CD14+ Monocytes,donor_1,True,False,-8.695493
AAACCGTGTATGCG-1,522,0.012245,980.0,NK cells,donor_2,False,False,2.065218

`across` expands one expression over selected columns.

In [21]:
adata.ap.mutate(
    obs=ap.across(ap.starts_with("n_"), lambda name: ap.col(name) / 1000, names="{col}_k")
).obs.head()

,n_genes,percent_mito,n_counts,louvain,donor_id,n_genes_k,n_counts_k
index,,,,,,,
AAACATACAACCAC-1,781,0.030178,2419.0,CD4 T cells,donor_1,0.781,2.419
AAACATTGAGCTAC-1,1352,0.037936,4903.0,B cells,donor_2,1.352,4.903
AAACATTGATCAGC-1,1131,0.008897,3147.0,CD4 T cells,donor_3,1.131,3.147
AAACCGTGCTTCCG-1,960,0.017431,2639.0,CD14+ Monocytes,donor_1,0.960,2.639
AAACCGTGTATGCG-1,522,0.012245,980.0,NK cells,donor_2,0.522,0.980

`summarize` reduces to a pandas DataFrame rather than an AnnData object.

In [22]:
adata.ap.summarize(
    obs={"cells": ap.n(), "median_genes": ap.median("n_genes")},
    raw={"mean_NKG7": ap.mean("NKG7")},
    by="louvain",
).round(3)

             louvain  cells  median_genes  mean_NKG7
0        CD4 T cells   1144         809.0      0.119
1            B cells    342         677.0      0.061
2    CD14+ Monocytes    480         859.0      0.162
3           NK cells    154         890.0      3.102
4        CD8 T cells    316         824.5      1.877
5  FCGR3A+ Monocytes    150        1272.0      0.303
6    Dendritic cells     37        1544.0      0.303
7     Megakaryocytes     15         364.0      0.285

## Reuse groups

In [23]:
grouped = adata.ap.group_by(obs="louvain")
grouped.group_keys()

             louvain
0        CD4 T cells
1            B cells
2    CD14+ Monocytes
3           NK cells
4        CD8 T cells
5  FCGR3A+ Monocytes
6    Dendritic cells
7     Megakaryocytes

In [24]:
key, group = next(iter(grouped))
key, group.n_obs

({'louvain': 'CD4 T cells'}, 1144)

In [25]:
grouped.count(sort=True)

             louvain     n
0        CD4 T cells  1144
1    CD14+ Monocytes   480
2            B cells   342
3        CD8 T cells   316
4           NK cells   154
5  FCGR3A+ Monocytes   150
6    Dendritic cells    37
7     Megakaryocytes    15

Grouped `mutate` evaluates window helpers such as `row_number` within each group.

In [26]:
grouped.mutate(
    obs={"within_type": ap.row_number(), "depth_rank": ap.min_rank("n_counts", descending=True)}
).ungroup().obs.head()

,n_genes,percent_mito,n_counts,louvain,donor_id,within_type,depth_rank
index,,,,,,,
AAACATACAACCAC-1,781,0.030178,2419.0,CD4 T cells,donor_1,1,497.0
AAACATTGAGCTAC-1,1352,0.037936,4903.0,B cells,donor_2,1,9.0
AAACATTGATCAGC-1,1131,0.008897,3147.0,CD4 T cells,donor_3,2,108.0
AAACCGTGCTTCCG-1,960,0.017431,2639.0,CD14+ Monocytes,donor_1,1,186.0
AAACCGTGTATGCG-1,522,0.012245,980.0,NK cells,donor_2,1,153.0

In [27]:
grouped.slice_max(ap.col("n_counts"), n=1).ungroup().obs[["louvain", "n_counts"]]

                            louvain  n_counts
index
CATACTTGGGTTAC-1        CD4 T cells    7167.0
CAGGTTGAGGATCT-1            B cells    8011.0
AACCTACTGTGAGG-1    CD14+ Monocytes    5682.0
CAGTTTACACACGT-1           NK cells    5343.0
GCCTCAACTCTTTG-1        CD8 T cells    5981.0
ATTTAGGAACCATG-1  FCGR3A+ Monocytes    5677.0
GGGCCAACCTTGGA-1    Dendritic cells    8415.0
ACGAACTGGCTATG-1     Megakaryocytes    8875.0

## Build tidy tables

In [28]:
adata.ap.to_df(
    obs=["louvain"],
    raw=["MS4A1", "CD79A"],
    obsm={"X_pca": ["0", "1"]},
    max_matrix_values=4 * adata.n_obs,
).head()

                          louvain  raw_MS4A1  raw_CD79A    X_pca_0   X_pca_1
index
AAACATACAACCAC-1      CD4 T cells        0.0        0.0   5.556233  0.257714
AAACATTGAGCTAC-1          B cells    1.94591   1.386294   7.209530  7.481985
AAACATTGATCAGC-1      CD4 T cells        0.0        0.0   2.694438 -1.583658
AAACCGTGCTTCCG-1  CD14+ Monocytes        0.0        0.0 -10.143295 -1.368530
AAACCGTGTATGCG-1         NK cells        0.0        0.0  -1.112816 -8.152788

In [29]:
tidy = adata.ap.to_tidy(
    obs=["louvain"], raw=["MS4A1", "CD79A"], max_matrix_values=2 * adata.n_obs
)
tidy.head()

           obs_name feature     value      louvain
0  AAACATACAACCAC-1   MS4A1       0.0  CD4 T cells
1  AAACATACAACCAC-1   CD79A       0.0  CD4 T cells
2  AAACATTGAGCTAC-1   MS4A1   1.94591      B cells
3  AAACATTGAGCTAC-1   CD79A  1.386294      B cells
4  AAACATTGATCAGC-1   MS4A1       0.0  CD4 T cells

In [30]:
ap.pivot_wider(
    tidy, id_cols=["obs_name", "louvain"], names_from="feature", values_from="value"
).head()

           obs_name          louvain     CD79A    MS4A1
0  AAACATACAACCAC-1      CD4 T cells       0.0      0.0
1  AAACATTGAGCTAC-1          B cells  1.386294  1.94591
2  AAACATTGATCAGC-1      CD4 T cells       0.0      0.0
3  AAACCGTGCTTCCG-1  CD14+ Monocytes       0.0      0.0
4  AAACCGTGTATGCG-1         NK cells       0.0      0.0

PCA loadings live in `varm` and come out through `as_frame`.

In [31]:
adata.ap.as_frame("varm", key="PCs", select=["0", "1"]).head().round(3)

             0      1
index
TNFRSF4 -0.026  0.003
CPSF3L  -0.008  0.009
ATAD3C  -0.003  0.003
C1orf86  0.011 -0.000
RER1     0.014  0.027

The pandas-only helpers cover common tidyr-style list-column and string workflows.

In [32]:
nested = ap.nest(
    adata.obs.reset_index(), by="louvain", columns=["index", "n_genes", "n_counts"]
)
nested

/exports/para-lipg-hpc/mdmanurung/_hobby/annplyr/src/annplyr/_verbs.py:2175: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for key, group in data.groupby(by_columns, sort=False, dropna=False):

             louvain                                               data
0        CD4 T cells                   index  n_genes  n_counts
0   ...
1            B cells                  index  n_genes  n_counts
0    ...
2    CD14+ Monocytes                  index  n_genes  n_counts
0    ...
3           NK cells                  index  n_genes  n_counts
0    ...
4        CD8 T cells                  index  n_genes  n_counts
0    ...
5  FCGR3A+ Monocytes                  index  n_genes  n_counts
0    ...
6    Dendritic cells                 index  n_genes  n_counts
0   AA...
7     Megakaryocytes                 index  n_genes  n_counts
0   AC...

In [33]:
ap.unnest(nested, "data").head()

       louvain             index  n_genes  n_counts
0  CD4 T cells  AAACATACAACCAC-1      781    2419.0
1  CD4 T cells  AAACATTGATCAGC-1     1131    3147.0
2  CD4 T cells  AAACGCTGTAGCCA-1      533    1275.0
3  CD4 T cells  AAACTTGATCCAGA-1      751    2388.0
4  CD4 T cells  AAAGAGACGAGATA-1      866    2410.0

In [34]:
panel = pd.DataFrame(
    {"panel": ["b_cell", "cytotoxic"], "markers": ["MS4A1,CD79A", "NKG7,GNLY"]}
)
ap.separate_rows(panel, "markers")

       panel markers
0     b_cell   MS4A1
1     b_cell   CD79A
2  cytotoxic    NKG7
3  cytotoxic    GNLY

## Compose with project code

In [35]:
def cell_type_counts(data):
    return data.ap.count("louvain", sort=True)


adata.ap.pipe(cell_type_counts)

             louvain     n
0        CD4 T cells  1144
1    CD14+ Monocytes   480
2            B cells   342
3        CD8 T cells   316
4           NK cells   154
5  FCGR3A+ Monocytes   150
6    Dendritic cells    37
7     Megakaryocytes    15

`annplyr` verbs chain naturally before the final `pipe` call.

In [36]:
(
    adata.ap.filter(obs=ap.col("percent_mito") < 0.03)
    .ap.mutate(raw={"b_score": (ap.col("MS4A1") + ap.col("CD79A")) / 2})
    .ap.pipe(lambda data: data.ap.summarize(obs={"mean_b_score": ap.mean("b_score")}, by="louvain"))
    .round(3)
)

             louvain  mean_b_score
0        CD4 T cells         0.034
1    CD14+ Monocytes         0.032
2           NK cells         0.028
3        CD8 T cells         0.023
4  FCGR3A+ Monocytes         0.051
5            B cells         1.208
6    Dendritic cells         0.111
7     Megakaryocytes         0.029